version: "3.7"

services:
  db-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: pimcs
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  pimcs:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db-mysql
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge